export const actionPokemon = {
	BUY_POKEMONS: 'BUY POKEMONS',
	FIND_POKEMON: 'FIND POKEMON',
	LIST_POKEMON: 'LIST POKEMON',
	SET_POKEMONS: 'SET POKEMONS'
}

export const actionUi = {
	SET_LOADING: 'SET LOADING'
}
